import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html Lang="en">
      <body>
        <div className="main"><div className="gradient" /></div>

        <main className="app">{children}</main>
      </body>
    </html>
  );
}
